# Generated by Django 3.2.5 on 2021-07-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_setup', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('movie_type', models.CharField(choices=[('Movies', 'Movies'), ('TV Series', 'TV Series')], max_length=20)),
                ('release_year', models.IntegerField()),
                ('runtime', models.CharField(max_length=100)),
                ('video_type', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_type', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('tags', models.TextField(blank=True, max_length=500, null=True)),
                ('film_rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_setup.filmratings')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_setup.languages')),
            ],
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150)),
                ('site_link', models.TextField(blank=True)),
                ('rating', models.FloatField(null=True)),
                ('site_icon', models.TextField(blank=True, max_length=255, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'movies_user_ratings',
            },
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_setup.languages')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='MovieWriters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.persons')),
            ],
            options={
                'db_table': 'movies_movie_writers',
            },
        ),
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.TextField(blank=True, null=True)),
                ('thumb', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'movies_movie_images',
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_setup.genres')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'movies_movie_genres',
            },
        ),
        migrations.CreateModel(
            name='MovieFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'movies_movie_files',
            },
        ),
        migrations.CreateModel(
            name='MovieDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.persons')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'movies_movie_directors',
            },
        ),
        migrations.CreateModel(
            name='MovieCasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.persons')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'movies_movie_casts',
            },
        ),
    ]
